name: Publish Pre-Release Nuget 

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  build:
    name: "Publish Pre-Release Nugets"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4   

    - name: Restore Nuget Packages
      run: dotnet restore EstateReporting.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/transactionprocessing/api/v3/index.json

    - name: Build Code
      run: dotnet build EstateReporting.sln --configuration Release
      
    - name: Get the last version
      id: get_version
      #run: echo ::set-output name=VERSION::$(git tag --sort=committerdate  | tail -1)
      run: echo "lastVersion=::$(git tag --sort=committerdate  | tail -1)" >> $GITHUB_ENV

    
    - name: Print Version
      id: next_version
      run: echo $lastVersion

    - name: Build and Publish Nuget Packages
      run: |
        dotnet pack "EstateReporting.Database\EstateReporting.Database.csproj" /p:PackageVersion=${{ steps.next_version.outputs.VERSION }} --output Nugets -c Release            
        dotnet nuget push Nugets/EstateReporting.Database.${{ steps.next_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.MYGET_APIKEY }} --source https://www.myget.org/F/transactionprocessing/api/v2/package      
        dotnet pack "EstateReporting.Client\EstateReporting.Client.csproj" /p:PackageVersion=${{ steps.next_version.outputs.VERSION }} --output Nugets -c Release            
        dotnet nuget push Nugets/EstateReporting.Client.${{ steps.next_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.MYGET_APIKEY }} --source https://www.myget.org/F/transactionprocessing/api/v2/package      
