name: Build and Test Pull Requests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: "Build and Test Pull Requests"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.3.4

    - name: test
      run: |
        curl --http2 .

    - name: Restore Nuget Packages
      run: dotnet restore EstateReporting.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/transactionprocessing/api/v3/index.json

    - name: Build Code
      run: dotnet build EstateReporting.sln --configuration Release

    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "EstateReporting.BusinessLogic.Tests\EstateReporting.BusinessLogic.Tests.csproj"
        dotnet test "EstateReporting.Repository.Tests\EstateReporting.Repository.Tests.csproj"

    - name: Build Docker Image
      run: docker build . --file EstateReporting/Dockerfile --tag estatereporting:latest
        
    - name: Run Integration Tests
      run: dotnet test "EstateReporting.IntegrationTests\EstateReporting.IntegrationTests.csproj" --filter Category=PRTest